name: Unzip file

on:
  push:
    paths:
      - 'source.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip the file
        run: |
          unzip source.zip -d unzipped

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add unzipped
          git commit -m "فك ضغط الملف تلقائيًا"
          git push
