name: Update Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON data to save'
        required: true
        default: '[]'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Save new data
        run: |
          echo '${{ github.event.inputs.data }}' > data.json
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update data via GitHub Actions"
          git push
